steps:
    - name: 'node'
      entrypoint: 'yarn'
      args: ['install']
    - name: node
      entrypoint: yarn
      args: ['build']
    - name: asia-south1-docker.pkg.dev/kiranbansode-votesub/gcf-artifacts
      args: ['hosting:channel:deploy', 'testing', '--project=kiranbansode-votesub']
