/* eslint-disable camelcase */
import { getList } from 'country-list-with-dial-code-and-flag';
import { nanoid } from 'nanoid';

export interface ICountryOption {
    id: string;
    value: string;
    option: string;
    name: string;
}

export const countryCodelabelsCreator = () => {
    const countryCodes = getList();
    const options: ICountryOption[] = [];

    countryCodes.forEach(({ dial_code, name, flag }) => {
        options.push({
            value: dial_code,
            option: `${flag} ${name}: ${dial_code}`,
            id: nanoid(),
            name,
        });
    });

    return options;
};

// console.log(JSON.stringify(countryCodelabelsCreator()));

// const countryCodelabels: ICountryOption[] = [
//     { value: '0', option: 'Please Select A Country', id: 'Fa6yaFhOrMy_GRhuKp9AC', name: 'unknown' },
//     {
//         value: '+93',
//         option: '🇦🇫 Afghanistan : +93',
//         id: 'giMo8tV9GF_oJafjREH8O',
//         name: 'Afghanistan',
//     },
//     { value: '+91', option: '🇮🇳 India : +91', id: 'zfdK6uZ8hc9qOqy9dzxkf', name: 'India' },
// ];

const countryCodelabels: ICountryOption[] = [
    {
        value: '+93',
        option: '🇦🇫 Afghanistan: +93',
        id: 'YWG8iwj4Na6g_H66hUrDX',
        name: 'Afghanistan',
    },
    { value: '+355', option: '🇦🇱 Albania: +355', id: 'soeiYQ9esMFqSwjsy_kHu', name: 'Albania' },
    { value: '+213', option: '🇩🇿 Algeria: +213', id: 'tjrHJgJkrcZZCIBZxEQtx', name: 'Algeria' },
    {
        value: '+1684',
        option: '🇦🇸 AmericanSamoa: +1684',
        id: 'U2D9HLTPZmMyrpkPsS31N',
        name: 'AmericanSamoa',
    },
    { value: '+376', option: '🇦🇩 Andorra: +376', id: 'p2f__X92GT5zZH0VnhWRH', name: 'Andorra' },
    { value: '+244', option: '🇦🇴 Angola: +244', id: 'iAu_7EBUrEd8vigPLDtet', name: 'Angola' },
    { value: '+1264', option: '🇦🇮 Anguilla: +1264', id: 'ZreAhBF9BMmY9chEq-JnG', name: 'Anguilla' },
    {
        value: '+672',
        option: '🇦🇶 Antarctica: +672',
        id: 'nsu5zlKesiXAXSnraqjE7',
        name: 'Antarctica',
    },
    {
        value: '+1268',
        option: '🇦🇬 Antigua and Barbuda: +1268',
        id: 'kkEDx-6RQ-oKfN0Il7wTj',
        name: 'Antigua and Barbuda',
    },
    { value: '+54', option: '🇦🇷 Argentina: +54', id: 'O1W77R0F-q3QNjji-zCBJ', name: 'Argentina' },
    { value: '+374', option: '🇦🇲 Armenia: +374', id: 'xtRBfaC1vye0_grFBd4Ik', name: 'Armenia' },
    { value: '+297', option: '🇦🇼 Aruba: +297', id: 'oXpgDN5pmmvnLvB1UqBPH', name: 'Aruba' },
    { value: '+61', option: '🇦🇺 Australia: +61', id: '-j3UFpXWslaV-C-tJpaK6', name: 'Australia' },
    { value: '+43', option: '🇦🇹 Austria: +43', id: 'oBVykHvwOTQ24pSsx_cvq', name: 'Austria' },
    {
        value: '+994',
        option: '🇦🇿 Azerbaijan: +994',
        id: 'wEY7HZnyYdvt2JiTzm_Qv',
        name: 'Azerbaijan',
    },
    { value: '+1242', option: '🇧🇸 Bahamas: +1242', id: 'WisfF-A2EnMpep8l86U1o', name: 'Bahamas' },
    { value: '+973', option: '🇧🇭 Bahrain: +973', id: 'MAf_bTrS7phUdob-4IrN5', name: 'Bahrain' },
    {
        value: '+880',
        option: '🇧🇩 Bangladesh: +880',
        id: 'wZ89yiyMCOb9sGHESH3OI',
        name: 'Bangladesh',
    },
    { value: '+1246', option: '🇧🇧 Barbados: +1246', id: 'JTZ3oKNvhLkUg0egRmzVE', name: 'Barbados' },
    { value: '+375', option: '🇧🇾 Belarus: +375', id: 'it2534XomnfF2K_ghDZly', name: 'Belarus' },
    { value: '+32', option: '🇧🇪 Belgium: +32', id: '4ZabJHxM4rRmunU1K8XLU', name: 'Belgium' },
    { value: '+501', option: '🇧🇿 Belize: +501', id: 'ASqD2B5VANdmNoCthB-p-', name: 'Belize' },
    { value: '+229', option: '🇧🇯 Benin: +229', id: 'stGeKWoFEEqHkxuz9DjKb', name: 'Benin' },
    { value: '+1441', option: '🇧🇲 Bermuda: +1441', id: 'NbRQiqnjWM_DKn8gFt93W', name: 'Bermuda' },
    { value: '+975', option: '🇧🇹 Bhutan: +975', id: 'Mpxa2vZEl2JYIrK4nHEp8', name: 'Bhutan' },
    {
        value: '+591',
        option: '🇧🇴 Bolivia, Plurinational State of: +591',
        id: 'CyS5b11F3RoodjSeCuzb2',
        name: 'Bolivia, Plurinational State of',
    },
    {
        value: '+387',
        option: '🇧🇦 Bosnia and Herzegovina: +387',
        id: 'dH_JeSH-BtwRO6Ro0nI2T',
        name: 'Bosnia and Herzegovina',
    },
    { value: '+267', option: '🇧🇼 Botswana: +267', id: 'cTDKKi6mOyN-KMqtw7Dqx', name: 'Botswana' },
    { value: '+55', option: '🇧🇷 Brazil: +55', id: 'Py_eI4twg4ynrzEZfQv_J', name: 'Brazil' },
    {
        value: '+246',
        option: '🇮🇴 British Indian Ocean Territory: +246',
        id: 'oh6sAPcLKL7TRH8U57vI0',
        name: 'British Indian Ocean Territory',
    },
    {
        value: '+673',
        option: '🇧🇳 Brunei Darussalam: +673',
        id: 'kcBvwdkGCjQAnZwMAzi1E',
        name: 'Brunei Darussalam',
    },
    { value: '+359', option: '🇧🇬 Bulgaria: +359', id: 'QpN0eHvFYQJZ55fls0LBW', name: 'Bulgaria' },
    {
        value: '+226',
        option: '🇧🇫 Burkina Faso: +226',
        id: 'nbdETYcnwJDB6hLsd9Dmz',
        name: 'Burkina Faso',
    },
    { value: '+257', option: '🇧🇮 Burundi: +257', id: 'XgdSBMk550hFgnDH7-LyJ', name: 'Burundi' },
    { value: '+855', option: '🇰🇭 Cambodia: +855', id: 'SgOMf2pLAaPzR53z1EuMj', name: 'Cambodia' },
    { value: '+237', option: '🇨🇲 Cameroon: +237', id: 'eudd7rb2Z153BZDYydF9l', name: 'Cameroon' },
    { value: '+1', option: '🇨🇦 Canada: +1', id: 'CFNFfkEH1slpziWT_EAcC', name: 'Canada' },
    {
        value: '+238',
        option: '🇨🇻 Cape Verde: +238',
        id: 'M9dUsB0S4w0pvPxnGb7u7',
        name: 'Cape Verde',
    },
    {
        value: '+345',
        option: '🇰🇾 Cayman Islands: +345',
        id: '1A8uofFyoOv9oTwypJlyB',
        name: 'Cayman Islands',
    },
    {
        value: '+236',
        option: '🇨🇫 Central African Republic: +236',
        id: '6-MKy6obqpI_O1P9Uc6P8',
        name: 'Central African Republic',
    },
    { value: '+235', option: '🇹🇩 Chad: +235', id: 'Ek1dqPkxPTs3Bq_oXMHqE', name: 'Chad' },
    { value: '+56', option: '🇨🇱 Chile: +56', id: 'W5m6LD-CydausTGNerfVr', name: 'Chile' },
    { value: '+86', option: '🇨🇳 China: +86', id: 'lhzCSZG-9mv_YDnSpJHz7', name: 'China' },
    {
        value: '+61',
        option: '🇨🇽 Christmas Island: +61',
        id: 'jVmS0DrbZdqsX_fRMo-i2',
        name: 'Christmas Island',
    },
    {
        value: '+61',
        option: '🇨🇨 Cocos (Keeling) Islands: +61',
        id: '6vYTklDFxj_IE7MqxxqW8',
        name: 'Cocos (Keeling) Islands',
    },
    { value: '+57', option: '🇨🇴 Colombia: +57', id: '03HdIsJJk5sx6b8NEYHVR', name: 'Colombia' },
    { value: '+269', option: '🇰🇲 Comoros: +269', id: 'ebn121xmsU2LPUE538NCs', name: 'Comoros' },
    { value: '+242', option: '🇨🇬 Congo: +242', id: 'rV1zCSEgViyK5dcQdE9O7', name: 'Congo' },
    {
        value: '+243',
        option: '🇨🇩 Congo, The Democratic Republic of the: +243',
        id: '0Awn-vsku0PaR8A2A2_L3',
        name: 'Congo, The Democratic Republic of the',
    },
    {
        value: '+682',
        option: '🇨🇰 Cook Islands: +682',
        id: 'UibymDHoeaEHfw-Ajc2mb',
        name: 'Cook Islands',
    },
    {
        value: '+506',
        option: '🇨🇷 Costa Rica: +506',
        id: 'AZiZsYs3j8LAXjMfzZYnQ',
        name: 'Costa Rica',
    },
    {
        value: '+225',
        option: "🇨🇮 Cote d'Ivoire: +225",
        id: 'iRuHCoIMJURq37K7CfwgR',
        name: "Cote d'Ivoire",
    },
    { value: '+385', option: '🇭🇷 Croatia: +385', id: 's4oESIe1U9eb8MDo2znyc', name: 'Croatia' },
    { value: '+53', option: '🇨🇺 Cuba: +53', id: 'zh4ygkDsvpG-47SM156B7', name: 'Cuba' },
    { value: '+357', option: '🇨🇾 Cyprus: +357', id: 'dytT6ZPV72SFc1Z0SQutk', name: 'Cyprus' },
    {
        value: '+420',
        option: '🇨🇿 Czech Republic: +420',
        id: 'OChwPUskqTHY1Fwt-8Z4s',
        name: 'Czech Republic',
    },
    { value: '+45', option: '🇩🇰 Denmark: +45', id: 'CWVIpTpNOht2esi1GYG9-', name: 'Denmark' },
    { value: '+253', option: '🇩🇯 Djibouti: +253', id: 'r50JGRbGgC34urjhqHMKd', name: 'Djibouti' },
    { value: '+1767', option: '🇩🇲 Dominica: +1767', id: 'nWxjud_hAVWOsm_ldlVly', name: 'Dominica' },
    {
        value: '+1849',
        option: '🇩🇴 Dominican Republic: +1849',
        id: '1cFyX1woa2A-OI2dTA_7Y',
        name: 'Dominican Republic',
    },
    { value: '+593', option: '🇪🇨 Ecuador: +593', id: 'zVT8JczSE9TW-xOrLVzgN', name: 'Ecuador' },
    { value: '+20', option: '🇪🇬 Egypt: +20', id: 'oejJYVP3lRV2ftgykVJ5C', name: 'Egypt' },
    {
        value: '+503',
        option: '🇸🇻 El Salvador: +503',
        id: 'KtUaJx2s1Zl8lskk7ZIj0',
        name: 'El Salvador',
    },
    {
        value: '+240',
        option: '🇬🇶 Equatorial Guinea: +240',
        id: 'FX_CpThSJlYehJAWXTsEx',
        name: 'Equatorial Guinea',
    },
    { value: '+291', option: '🇪🇷 Eritrea: +291', id: 'cCr1JKfabT2c7rGV49XyR', name: 'Eritrea' },
    { value: '+372', option: '🇪🇪 Estonia: +372', id: 'EnnxwW-3vufdPEC4eakqR', name: 'Estonia' },
    { value: '+251', option: '🇪🇹 Ethiopia: +251', id: 'sa3TN16Mz-9Zc1LVqaNjY', name: 'Ethiopia' },
    {
        value: '+500',
        option: '🇫🇰 Falkland Islands (Malvinas): +500',
        id: 'eKvYoXweTYoFpT_P9ciP7',
        name: 'Falkland Islands (Malvinas)',
    },
    {
        value: '+298',
        option: '🇫🇴 Faroe Islands: +298',
        id: 'ImMn8IN4PaZks1o_bbw-W',
        name: 'Faroe Islands',
    },
    { value: '+679', option: '🇫🇯 Fiji: +679', id: 'XyvhDptuT7FXVtvlkE8uT', name: 'Fiji' },
    { value: '+358', option: '🇫🇮 Finland: +358', id: 'IHxtAdlxderhSQ2IHwVej', name: 'Finland' },
    { value: '+33', option: '🇫🇷 France: +33', id: 'gNAt0Z8EvHrsdo-D53kXc', name: 'France' },
    {
        value: '+594',
        option: '🇬🇫 French Guiana: +594',
        id: 'zcdd6CNGcaB4x2R1qnZIe',
        name: 'French Guiana',
    },
    {
        value: '+689',
        option: '🇵🇫 French Polynesia: +689',
        id: 'JzB7n4nzDD4r657Dk3Jzj',
        name: 'French Polynesia',
    },
    { value: '+241', option: '🇬🇦 Gabon: +241', id: 'F7j6FSxjgWvMhOb67f-00', name: 'Gabon' },
    { value: '+220', option: '🇬🇲 Gambia: +220', id: 'i4pQxD-RKP7BZjM9sdzmj', name: 'Gambia' },
    { value: '+995', option: '🇬🇪 Georgia: +995', id: 'FZSdvikP8SNGHvO95KJbo', name: 'Georgia' },
    { value: '+49', option: '🇩🇪 Germany: +49', id: '0UBbkFnkw2JpljFUefNgo', name: 'Germany' },
    { value: '+233', option: '🇬🇭 Ghana: +233', id: 'h8rkl9yiS8iwg09mrzMuA', name: 'Ghana' },
    { value: '+350', option: '🇬🇮 Gibraltar: +350', id: 'sedohtUGEueg0pWm-0l0v', name: 'Gibraltar' },
    { value: '+30', option: '🇬🇷 Greece: +30', id: 'GzP7Oc_LS04vwzWJLlrNb', name: 'Greece' },
    { value: '+299', option: '🇬🇱 Greenland: +299', id: 'OKdWvOstaYgtf_rlONB8J', name: 'Greenland' },
    { value: '+1473', option: '🇬🇩 Grenada: +1473', id: '0gPbiOO1ElkcgwSLbPbYO', name: 'Grenada' },
    {
        value: '+590',
        option: '🇬🇵 Guadeloupe: +590',
        id: 'TSTx1RmOEIv1GKJY8UtUg',
        name: 'Guadeloupe',
    },
    { value: '+1671', option: '🇬🇺 Guam: +1671', id: 'K47T-AnEqt5z5x4BBRK6c', name: 'Guam' },
    { value: '+502', option: '🇬🇹 Guatemala: +502', id: '96l7VzCU5Yd3OPjHlCUkx', name: 'Guatemala' },
    { value: '+44', option: '🇬🇬 Guernsey: +44', id: 'jDPNV6jBeqPM0fTz6z2pa', name: 'Guernsey' },
    { value: '+224', option: '🇬🇳 Guinea: +224', id: 'CZ5z-UJPX1rbmzk4PPg_2', name: 'Guinea' },
    {
        value: '+245',
        option: '🇬🇼 Guinea-Bissau: +245',
        id: 'YUk6KdUUVW0JwkQsMJ0jV',
        name: 'Guinea-Bissau',
    },
    { value: '+592', option: '🇬🇾 Guyana: +592', id: '2FjcKOJ7S_NGWWJEnkZ7d', name: 'Guyana' },
    { value: '+509', option: '🇭🇹 Haiti: +509', id: 'crPOoyv-gtnZCpLFzBuac', name: 'Haiti' },
    {
        value: '+379',
        option: '🇻🇦 Holy See (Vatican City State): +379',
        id: 'aeMbjQlAjO8HkmUttYVIf',
        name: 'Holy See (Vatican City State)',
    },
    { value: '+504', option: '🇭🇳 Honduras: +504', id: 'Om8Qd-ASi1k_X2AwNh57f', name: 'Honduras' },
    { value: '+852', option: '🇭🇰 Hong Kong: +852', id: '0Uk5OvCMoyjaIgxFXznW3', name: 'Hong Kong' },
    { value: '+36', option: '🇭🇺 Hungary: +36', id: '_oBUG4j1eBn-GuszRC4UL', name: 'Hungary' },
    { value: '+354', option: '🇮🇸 Iceland: +354', id: 'SqwJv4HuKo3T4NCHsOKdF', name: 'Iceland' },
    { value: '+91', option: '🇮🇳 India: +91', id: 'oC4e441xW7lPHxo4ZcE6W', name: 'India' },
    { value: '+62', option: '🇮🇩 Indonesia: +62', id: 'ag-PecUsp7FDpZ9WlTJoy', name: 'Indonesia' },
    {
        value: '+98',
        option: '🇮🇷 Iran, Islamic Republic of: +98',
        id: 'bHbpBCJmg9hRiM3AybFBV',
        name: 'Iran, Islamic Republic of',
    },
    { value: '+964', option: '🇮🇶 Iraq: +964', id: 'Iefma_N5S00Ap5zDbGla_', name: 'Iraq' },
    { value: '+353', option: '🇮🇪 Ireland: +353', id: 'lcYEjfsCxhyu33_hdFr97', name: 'Ireland' },
    {
        value: '+44',
        option: '🇮🇲 Isle of Man: +44',
        id: 'o_1WWlTVCxdi-TPN8GZHW',
        name: 'Isle of Man',
    },
    { value: '+972', option: '🇮🇱 Israel: +972', id: 'U_7n8SYo_tt091lTIrJ5Q', name: 'Israel' },
    { value: '+39', option: '🇮🇹 Italy: +39', id: 'iCw0FILri1l_K9H7BJgae', name: 'Italy' },
    { value: '+1876', option: '🇯🇲 Jamaica: +1876', id: 'EWlmn7IqsKvhJLFyKE5TS', name: 'Jamaica' },
    { value: '+81', option: '🇯🇵 Japan: +81', id: 'Kx3wahtOj5qiFjHkycdOU', name: 'Japan' },
    { value: '+44', option: '🇯🇪 Jersey: +44', id: 'DvQPXsyazV2pN_-wvNoC8', name: 'Jersey' },
    { value: '+962', option: '🇯🇴 Jordan: +962', id: 'JvjrPeKS09mNV1pDx2rA4', name: 'Jordan' },
    { value: '+77', option: '🇰🇿 Kazakhstan: +77', id: 'l6HjMOW7bT_8dRpxCLzfo', name: 'Kazakhstan' },
    { value: '+254', option: '🇰🇪 Kenya: +254', id: 'VFBlt2Tjy4tOgn6V5LZaR', name: 'Kenya' },
    { value: '+686', option: '🇰🇮 Kiribati: +686', id: '03w0PUkij2G-kqIlpURER', name: 'Kiribati' },
    {
        value: '+850',
        option: "🇰🇵 Korea, Democratic People's Republic of: +850",
        id: '1NCV17y4R9WD_wls7KA8W',
        name: "Korea, Democratic People's Republic of",
    },
    {
        value: '+82',
        option: '🇰🇷 Korea, Republic of: +82',
        id: 'LaUa7ZzFooYLcEmCpfH2-',
        name: 'Korea, Republic of',
    },
    { value: '+965', option: '🇰🇼 Kuwait: +965', id: 'vCV0fubSlwWboMHZRmlD6', name: 'Kuwait' },
    {
        value: '+996',
        option: '🇰🇬 Kyrgyzstan: +996',
        id: 'BBiXeCPi1CghlXQr9aG51',
        name: 'Kyrgyzstan',
    },
    {
        value: '+856',
        option: "🇱🇦 Lao People's Democratic Republic: +856",
        id: 'W5E-ArgxtteLeb-ZCckhf',
        name: "Lao People's Democratic Republic",
    },
    { value: '+371', option: '🇱🇻 Latvia: +371', id: 'MG_L25ptxWNEr2Jfe2O-z', name: 'Latvia' },
    { value: '+961', option: '🇱🇧 Lebanon: +961', id: '2UsEecHVHhqpH8tt3-tDb', name: 'Lebanon' },
    { value: '+266', option: '🇱🇸 Lesotho: +266', id: 'qdba7NVCjZODKKWMKF3PC', name: 'Lesotho' },
    { value: '+231', option: '🇱🇷 Liberia: +231', id: 'U6qJ3Duv86u0t6M4xGKhm', name: 'Liberia' },
    {
        value: '+218',
        option: '🇱🇾 Libyan Arab Jamahiriya: +218',
        id: 'ikVwI80pzUP6xJJxPUHqf',
        name: 'Libyan Arab Jamahiriya',
    },
    {
        value: '+423',
        option: '🇱🇮 Liechtenstein: +423',
        id: 'oj6wiN4DEFOrfyfBnwQDM',
        name: 'Liechtenstein',
    },
    { value: '+370', option: '🇱🇹 Lithuania: +370', id: '-IAYimUpFa_ugEZbZrS76', name: 'Lithuania' },
    {
        value: '+352',
        option: '🇱🇺 Luxembourg: +352',
        id: 'DTSkW-CgeQbGozK4gj_-Y',
        name: 'Luxembourg',
    },
    { value: '+853', option: '🇲🇴 Macao: +853', id: '6RtqRG3YioSeELrM6kDe1', name: 'Macao' },
    {
        value: '+389',
        option: '🇲🇰 Macedonia, The Former Yugoslav Republic of: +389',
        id: 'EO9ujmEPZE_Vkx2cMgPho',
        name: 'Macedonia, The Former Yugoslav Republic of',
    },
    {
        value: '+261',
        option: '🇲🇬 Madagascar: +261',
        id: 'QTR8PnuZE-3Mq3OdUd9jj',
        name: 'Madagascar',
    },
    { value: '+265', option: '🇲🇼 Malawi: +265', id: 'mq5KHIHjMBtiDiLeMxXCN', name: 'Malawi' },
    { value: '+60', option: '🇲🇾 Malaysia: +60', id: 'AEZwyNGBfNRpLxXDRNQyY', name: 'Malaysia' },
    { value: '+960', option: '🇲🇻 Maldives: +960', id: 'TS2QwvB3UpBQsp7H_pE2e', name: 'Maldives' },
    { value: '+223', option: '🇲🇱 Mali: +223', id: 'u4iKE9HtF3sFYLicGhO9u', name: 'Mali' },
    { value: '+356', option: '🇲🇹 Malta: +356', id: 'IXkeBssEAZfsHulktG-BS', name: 'Malta' },
    {
        value: '+692',
        option: '🇲🇭 Marshall Islands: +692',
        id: 'Z6dIGrh228JvKkL5YuRw8',
        name: 'Marshall Islands',
    },
    {
        value: '+596',
        option: '🇲🇶 Martinique: +596',
        id: 'XY5L3A9C7DMb2LFKIezsn',
        name: 'Martinique',
    },
    {
        value: '+222',
        option: '🇲🇷 Mauritania: +222',
        id: '2Zbt_3bkPGehnxkW1rYfu',
        name: 'Mauritania',
    },
    { value: '+230', option: '🇲🇺 Mauritius: +230', id: '-dloV9ccE0Qvq9XLDg2We', name: 'Mauritius' },
    { value: '+262', option: '🇾🇹 Mayotte: +262', id: 'mQP3QCNdkWQEgI_UIJSgh', name: 'Mayotte' },
    { value: '+52', option: '🇲🇽 Mexico: +52', id: 'pvemb3HE5ZyfUgXShTItA', name: 'Mexico' },
    {
        value: '+691',
        option: '🇫🇲 Micronesia, Federated States of: +691',
        id: '0LtEJ5TVsvEKZzOF45n2j',
        name: 'Micronesia, Federated States of',
    },
    {
        value: '+373',
        option: '🇲🇩 Moldova, Republic of: +373',
        id: 'utobt0Ee4U6tcgTIsAuQB',
        name: 'Moldova, Republic of',
    },
    { value: '+377', option: '🇲🇨 Monaco: +377', id: 'WtiVSY_C74-pgxu0Rs6O4', name: 'Monaco' },
    { value: '+976', option: '🇲🇳 Mongolia: +976', id: 'XE4bhOz6cCxY1I4XLO5yy', name: 'Mongolia' },
    {
        value: '+382',
        option: '🇲🇪 Montenegro: +382',
        id: 'qvVt0-O7eIa5FJvBpS2yg',
        name: 'Montenegro',
    },
    {
        value: '+1664',
        option: '🇲🇸 Montserrat: +1664',
        id: '7mw625XYottOlxAkKjA4r',
        name: 'Montserrat',
    },
    { value: '+212', option: '🇲🇦 Morocco: +212', id: 'AIK9j9ONY_yRKI9ZyHq0y', name: 'Morocco' },
    {
        value: '+258',
        option: '🇲🇿 Mozambique: +258',
        id: 'jMVB-pGywvu0H-t0QDndJ',
        name: 'Mozambique',
    },
    { value: '+95', option: '🇲🇲 Myanmar: +95', id: 'taV-AUtKK6urfiEYY7TIv', name: 'Myanmar' },
    { value: '+264', option: '🇳🇦 Namibia: +264', id: 'OYKqsMOk81i7kGr2glhvj', name: 'Namibia' },
    { value: '+674', option: '🇳🇷 Nauru: +674', id: 'K7e7SKExRCJtGYFynrPNT', name: 'Nauru' },
    { value: '+977', option: '🇳🇵 Nepal: +977', id: 'LkN0nSugresJ0TEQUV_Ni', name: 'Nepal' },
    {
        value: '+31',
        option: '🇳🇱 Netherlands: +31',
        id: 'OJaVGVzr1Y-EcmWYZqS8f',
        name: 'Netherlands',
    },
    {
        value: '+599',
        option: '🇦🇳 Netherlands Antilles: +599',
        id: 'XTkL7piIxznZa2_-fdlIX',
        name: 'Netherlands Antilles',
    },
    {
        value: '+687',
        option: '🇳🇨 New Caledonia: +687',
        id: 'GWQpcNRD74etcd7ft3zM6',
        name: 'New Caledonia',
    },
    {
        value: '+64',
        option: '🇳🇿 New Zealand: +64',
        id: '9j0dzBjMa8otHxdgdTZga',
        name: 'New Zealand',
    },
    { value: '+505', option: '🇳🇮 Nicaragua: +505', id: '8touL0sgjBAawkz5-GtPs', name: 'Nicaragua' },
    { value: '+227', option: '🇳🇪 Niger: +227', id: '4X10QEKKJRJVH2rEbaZlg', name: 'Niger' },
    { value: '+234', option: '🇳🇬 Nigeria: +234', id: '3CPHaTjIrNIPzOaD_Kw7H', name: 'Nigeria' },
    { value: '+683', option: '🇳🇺 Niue: +683', id: 'bF6PcA8Cv-ZgEvyu6cOen', name: 'Niue' },
    {
        value: '+672',
        option: '🇳🇫 Norfolk Island: +672',
        id: 'tNg2qTXb93k349c4HS37k',
        name: 'Norfolk Island',
    },
    {
        value: '+1670',
        option: '🇲🇵 Northern Mariana Islands: +1670',
        id: '38QklS15gyaBNz9lUkE9h',
        name: 'Northern Mariana Islands',
    },
    { value: '+47', option: '🇳🇴 Norway: +47', id: 'i4t7uDRJuN4L8B_mQnd7-', name: 'Norway' },
    { value: '+968', option: '🇴🇲 Oman: +968', id: '81dsfCjC4EDQmc64ioY_v', name: 'Oman' },
    { value: '+92', option: '🇵🇰 Pakistan: +92', id: '-AR7-F17h9NCp5T_AiSLE', name: 'Pakistan' },
    { value: '+680', option: '🇵🇼 Palau: +680', id: 'Z59rJCDBmwapGYR55fOr0', name: 'Palau' },
    {
        value: '+970',
        option: '🇵🇸 Palestinian Territory, Occupied: +970',
        id: 'jXwnqIZaoApfZyciCH9vr',
        name: 'Palestinian Territory, Occupied',
    },
    { value: '+507', option: '🇵🇦 Panama: +507', id: '69vs8lHHtkEeqzXWl_UQl', name: 'Panama' },
    {
        value: '+675',
        option: '🇵🇬 Papua New Guinea: +675',
        id: '2HNuW8xPg3Zujuygajkev',
        name: 'Papua New Guinea',
    },
    { value: '+595', option: '🇵🇾 Paraguay: +595', id: '8iBTiTg8us3yNPVrwDumA', name: 'Paraguay' },
    { value: '+51', option: '🇵🇪 Peru: +51', id: '0DeilZiXvyv8uQWSLCyQy', name: 'Peru' },
    {
        value: '+63',
        option: '🇵🇭 Philippines: +63',
        id: '7LFYL5-__OUVuyuwaBKg6',
        name: 'Philippines',
    },
    { value: '+872', option: '🇵🇳 Pitcairn: +872', id: 'uGaC3CIfl-F0f7LWgrC4j', name: 'Pitcairn' },
    { value: '+48', option: '🇵🇱 Poland: +48', id: 'n-1OMJ9zv5VsXkXbfPb24', name: 'Poland' },
    { value: '+351', option: '🇵🇹 Portugal: +351', id: 'VK2etcZibm42Z4pC6YN3F', name: 'Portugal' },
    {
        value: '+1939',
        option: '🇵🇷 Puerto Rico: +1939',
        id: 'HEqPWtJ3KqqX2ZX5s0D7O',
        name: 'Puerto Rico',
    },
    { value: '+974', option: '🇶🇦 Qatar: +974', id: '3fzan2DjDmh8YiNi8rHw7', name: 'Qatar' },
    { value: '+40', option: '🇷🇴 Romania: +40', id: 'sL47RZzc57YDGBgNdWg3l', name: 'Romania' },
    { value: '+7', option: '🇷🇺 Russia: +7', id: 'ot3yz3O8WOjW1BrR_ef70', name: 'Russia' },
    { value: '+250', option: '🇷🇼 Rwanda: +250', id: 'y1S0iKAzEc7kqQ6XvXxoA', name: 'Rwanda' },
    { value: '+262', option: '🇷🇪 Réunion: +262', id: 'lioPK7y6kkuRs4QAoDCmc', name: 'Réunion' },
    {
        value: '+590',
        option: '🇧🇱 Saint Barthélemy: +590',
        id: '21XjRN7ToKSbNll3a-Zpm',
        name: 'Saint Barthélemy',
    },
    {
        value: '+290',
        option: '🇸🇭 Saint Helena, Ascension and Tristan Da Cunha: +290',
        id: 'v9XISAIsUl0VSMsbxD9CG',
        name: 'Saint Helena, Ascension and Tristan Da Cunha',
    },
    {
        value: '+1869',
        option: '🇰🇳 Saint Kitts and Nevis: +1869',
        id: 'd_Ehf6jF-yhSMEkq9g_yL',
        name: 'Saint Kitts and Nevis',
    },
    {
        value: '+1758',
        option: '🇱🇨 Saint Lucia: +1758',
        id: 'uOrbza3lX9-rgN5O55jo9',
        name: 'Saint Lucia',
    },
    {
        value: '+590',
        option: '🇲🇫 Saint Martin: +590',
        id: 'MhQLizH723lgXEqDdIo4D',
        name: 'Saint Martin',
    },
    {
        value: '+508',
        option: '🇵🇲 Saint Pierre and Miquelon: +508',
        id: 'Z74ZpUKDj8Avgy_vhh1zs',
        name: 'Saint Pierre and Miquelon',
    },
    {
        value: '+1784',
        option: '🇻🇨 Saint Vincent and the Grenadines: +1784',
        id: 'NIvn-cZt8m_RyA66Oq0op',
        name: 'Saint Vincent and the Grenadines',
    },
    { value: '+685', option: '🇼🇸 Samoa: +685', id: '2Hl-MrwZbTHZzE2EU4jNR', name: 'Samoa' },
    {
        value: '+378',
        option: '🇸🇲 San Marino: +378',
        id: 'iQyytkl4MPMsLyBnFw2Bs',
        name: 'San Marino',
    },
    {
        value: '+239',
        option: '🇸🇹 Sao Tome and Principe: +239',
        id: 'qBx1xsvGiBCnYT4fvq-Ih',
        name: 'Sao Tome and Principe',
    },
    {
        value: '+966',
        option: '🇸🇦 Saudi Arabia: +966',
        id: 'NsfjCVNnPRycLtuAiptvE',
        name: 'Saudi Arabia',
    },
    { value: '+221', option: '🇸🇳 Senegal: +221', id: 'zYLwQmXVWdJY8HqLdDYRk', name: 'Senegal' },
    { value: '+381', option: '🇷🇸 Serbia: +381', id: 'cudiTmjuaBLzwgNe3ptUU', name: 'Serbia' },
    {
        value: '+248',
        option: '🇸🇨 Seychelles: +248',
        id: 'XRdPxrZo2HNyTk1CHIy0Z',
        name: 'Seychelles',
    },
    {
        value: '+232',
        option: '🇸🇱 Sierra Leone: +232',
        id: '29aPUBtbxmoD2kr2HZn-j',
        name: 'Sierra Leone',
    },
    { value: '+65', option: '🇸🇬 Singapore: +65', id: 'rQnePsI1KX1G4Q324z5T8', name: 'Singapore' },
    { value: '+421', option: '🇸🇰 Slovakia: +421', id: 'MkFHoZE5N5rq04aOReGvL', name: 'Slovakia' },
    { value: '+386', option: '🇸🇮 Slovenia: +386', id: 'tiIw3UrsIC34c93I5w5dM', name: 'Slovenia' },
    {
        value: '+677',
        option: '🇸🇧 Solomon Islands: +677',
        id: 'mN-gu9mGjZS3p2FFM3OUc',
        name: 'Solomon Islands',
    },
    { value: '+252', option: '🇸🇴 Somalia: +252', id: 'euCg7zB6Ak5cMxiPjjVba', name: 'Somalia' },
    {
        value: '+27',
        option: '🇿🇦 South Africa: +27',
        id: 'LAzC1Z7LKQDkMD779U29k',
        name: 'South Africa',
    },
    {
        value: '+500',
        option: '🇬🇸 South Georgia and the South Sandwich Islands: +500',
        id: 'XFTrQWJJGHu0uMDI-SK1Z',
        name: 'South Georgia and the South Sandwich Islands',
    },
    { value: '+34', option: '🇪🇸 Spain: +34', id: 'wDMEO-NJBDWMUq0-Ly5nl', name: 'Spain' },
    { value: '+94', option: '🇱🇰 Sri Lanka: +94', id: 'wnZ27v-0WsDqhpN-6F7mz', name: 'Sri Lanka' },
    { value: '+249', option: '🇸🇩 Sudan: +249', id: 'lvJjfqfS174MJ2uZXT3qw', name: 'Sudan' },
    {
        value: '+211',
        option: '🇸🇸 South Sudan: +211',
        id: 'aC6xiG-jWKbmIpcVLIGND',
        name: 'South Sudan',
    },
    { value: '+597', option: '🇸🇷 Suriname: +597', id: 'AirhkstjJN_FC3cnMplc5', name: 'Suriname' },
    {
        value: '+47',
        option: '🇸🇯 Svalbard and Jan Mayen: +47',
        id: 'UJGhowLcRrrm3jcVH0GRu',
        name: 'Svalbard and Jan Mayen',
    },
    { value: '+268', option: '🇸🇿 Swaziland: +268', id: 'LHEmHeQV8FGRguEupEYWD', name: 'Swaziland' },
    { value: '+46', option: '🇸🇪 Sweden: +46', id: '2ScqQIETulXS5vEm82ku2', name: 'Sweden' },
    {
        value: '+41',
        option: '🇨🇭 Switzerland: +41',
        id: 'Bwd6uNKyIm9LWIsBPFqup',
        name: 'Switzerland',
    },
    {
        value: '+963',
        option: '🇸🇾 Syrian Arab Republic: +963',
        id: 'iMM1SPeO1N-qjocaj2j9o',
        name: 'Syrian Arab Republic',
    },
    {
        value: '+886',
        option: '🇹🇼 Taiwan, Province of China: +886',
        id: 'MGY-5STIu8TJbQcrxq8_u',
        name: 'Taiwan, Province of China',
    },
    {
        value: '+992',
        option: '🇹🇯 Tajikistan: +992',
        id: 'cgXv82LpqCqq3fjGzg3aC',
        name: 'Tajikistan',
    },
    {
        value: '+255',
        option: '🇹🇿 Tanzania, United Republic of: +255',
        id: 'ijHekoOAQ2eewdg6816fK',
        name: 'Tanzania, United Republic of',
    },
    { value: '+66', option: '🇹🇭 Thailand: +66', id: '5vVqDXFwNPYc8efsTUbo2', name: 'Thailand' },
    {
        value: '+670',
        option: '🇹🇱 Timor-Leste: +670',
        id: '_extYicrpVPnATkvx41A4',
        name: 'Timor-Leste',
    },
    { value: '+228', option: '🇹🇬 Togo: +228', id: 'dZy7jPjH5oFKiT_UhcDtA', name: 'Togo' },
    { value: '+690', option: '🇹🇰 Tokelau: +690', id: 'vz5ZOnEWOZo_nED9le5SR', name: 'Tokelau' },
    { value: '+676', option: '🇹🇴 Tonga: +676', id: 'dedcE44uky3cb7b2TMvvn', name: 'Tonga' },
    {
        value: '+1868',
        option: '🇹🇹 Trinidad and Tobago: +1868',
        id: 'xPpy0fD11s1F4FIYUOsQR',
        name: 'Trinidad and Tobago',
    },
    { value: '+216', option: '🇹🇳 Tunisia: +216', id: '2t3dhHvkwMv3eMA_sH5XF', name: 'Tunisia' },
    { value: '+90', option: '🇹🇷 Turkey: +90', id: 'QXBRuFO02PGmHDpohhxDI', name: 'Turkey' },
    {
        value: '+993',
        option: '🇹🇲 Turkmenistan: +993',
        id: 'cJzTYt_CidThzDAGzsH7J',
        name: 'Turkmenistan',
    },
    {
        value: '+1649',
        option: '🇹🇨 Turks and Caicos Islands: +1649',
        id: '4KGchJJRSXjjAFhaU2w8b',
        name: 'Turks and Caicos Islands',
    },
    { value: '+688', option: '🇹🇻 Tuvalu: +688', id: 'x7pYJeahSVPIBUGZMXtkR', name: 'Tuvalu' },
    { value: '+256', option: '🇺🇬 Uganda: +256', id: 'bBWg92nLS0mVvK9Rw1JTl', name: 'Uganda' },
    { value: '+380', option: '🇺🇦 Ukraine: +380', id: 'kJEOHCT5_QA49-rec-C-T', name: 'Ukraine' },
    {
        value: '+971',
        option: '🇦🇪 United Arab Emirates: +971',
        id: '4xifVIfHgSqZFGlpcbPVp',
        name: 'United Arab Emirates',
    },
    {
        value: '+44',
        option: '🇬🇧 United Kingdom: +44',
        id: 'gQBu4wP-vzKYgVRsUKJXG',
        name: 'United Kingdom',
    },
    {
        value: '+1',
        option: '🇺🇸 United States: +1',
        id: 'GSpNRlUiUCkTM386Lv6ws',
        name: 'United States',
    },
    { value: '+598', option: '🇺🇾 Uruguay: +598', id: '2tMsl8AdcBWmNiOe2gEh_', name: 'Uruguay' },
    {
        value: '+998',
        option: '🇺🇿 Uzbekistan: +998',
        id: 'g1JwB_M6N0bLVFsnjKdMn',
        name: 'Uzbekistan',
    },
    { value: '+678', option: '🇻🇺 Vanuatu: +678', id: 'h3iOC0Mvr28ZVqY2Qi71D', name: 'Vanuatu' },
    {
        value: '+58',
        option: '🇻🇪 Venezuela, Bolivarian Republic of: +58',
        id: '6oo1_R7eIyWdTHMgHk_Rm',
        name: 'Venezuela, Bolivarian Republic of',
    },
    { value: '+84', option: '🇻🇳 Viet Nam: +84', id: 'tP_-rodLzvOpgKAtQB4WR', name: 'Viet Nam' },
    {
        value: '+1284',
        option: '🇻🇬 Virgin Islands, British: +1284',
        id: 'DYC5L_UZHTOl5Ip_xAQdv',
        name: 'Virgin Islands, British',
    },
    {
        value: '+1340',
        option: '🇻🇮 Virgin Islands, U.S.: +1340',
        id: 'HsNScnPHd1F-nLXCa7lOR',
        name: 'Virgin Islands, U.S.',
    },
    {
        value: '+681',
        option: '🇼🇫 Wallis and Futuna: +681',
        id: 'qzg8MXglFJS9IQi3yzQxw',
        name: 'Wallis and Futuna',
    },
    { value: '+967', option: '🇾🇪 Yemen: +967', id: 'L4CB3aDsa6cBlOf0OvEqo', name: 'Yemen' },
    { value: '+260', option: '🇿🇲 Zambia: +260', id: 'SkRmRw3xA8ghX2w4a4iOM', name: 'Zambia' },
    { value: '+263', option: '🇿🇼 Zimbabwe: +263', id: '2-MYDj77MtZXlFTzUXJAR', name: 'Zimbabwe' },
    {
        value: '+358',
        option: '🇦🇽 Åland Islands: +358',
        id: 'nDB0m33Xhz1jNnp-bCzWM',
        name: 'Åland Islands',
    },
];

export default countryCodelabels;
